### ISSUE TITLE
Ramps typo

### ISSUE THREAD

**Issue by tom131313** [bovlb/frc-tips#1]
An idea robot would be great to have; an ideal one, even better.
[typo](https://github.com/bovlb/frc-tips/tree/main/ramps#:~:text=An-,idea,-FRC%20robot%20would)

Also, [coast](https://github.com/bovlb/frc-tips/tree/main/coast-mode#:~:text=robot%20is%20disabled%2C-,bu,-there%20is%20no)

Thanks for your tips. I'll use them.
aka SLAB-Mr.Thomas

**Comment by bovlb** [comment]
Both typos fixed, thanks!  

Glad they were helpful.  Any topic suggestions?
